### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Stefannag** [narralabs/brackets#1]
Hi,

Once I open the extension, I got several errors including `Uncaught SyntaxError: Cannot use import statement outside a module`, that is `import './popup.css';`.

Do you know how can I fix that? 

Thanks! :)

**Comment by westoque** [comment]
hello @Stefannag sorry for the obviously super long reply. we are currently trying to actively maintain this project now. are you able to use it or still need any help? if not will be closing this issue. thank you.

**Comment by Stefannag** [comment]
> hello @Stefannag sorry for the obviously super long reply. we are currently trying to actively maintain this project now. are you able to use it or still need any help? if not will be closing this issue. thank you.

Hi. In the meanwhile I solve the issue - can't tell how, I really forgot.

**Comment by westoque** [comment]
@Stefannag thanks for the confirmation and glad to know it's working. will be closing this issue.
